# Generated by Django 5.1.3 on 2026-04-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = []
