# Generated by Django 5.1.3 on 2026-04-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_auto_20260409_0639"),
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicrecord",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name="academicrecord",
            options={},
        ),
        migrations.RenameField(
            model_name="academicrecord",
            old_name="date_entered",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="academicrecord",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="academicrecord",
            name="student_name",
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="attendance_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="attended_classes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="guidance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="meeting.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="total_classes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="external_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="internal_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="result",
            field=models.CharField(default="Fail", max_length=20),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="semester",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="total_marks",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="AcademicGuidance",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
