# Generated by Django 5.1.3 on 2026-04-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_academicrecord_subject_and_more"),
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicrecord",
            options={"ordering": ["semester", "subject"]},
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="project_file",
            field=models.FileField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="project_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="guidance_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="semester",
            field=models.IntegerField(
                choices=[
                    (1, "Semester 1"),
                    (2, "Semester 2"),
                    (3, "Semester 3"),
                    (4, "Semester 4"),
                    (5, "Semester 5"),
                    (6, "Semester 6"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_records",
                to="meeting.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicrecord",
            unique_together={("student", "semester", "subject")},
        ),
    ]
