# Generated by Django 5.1.3 on 2026-04-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_academicrecord_options_and_more"),
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicrecord",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="academicrecord",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="guidance_notes",
            field=models.TextField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="result",
            field=models.CharField(default="Fail", max_length=10),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="semester",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meeting.student"
            ),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="subject",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="projects/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.student",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="academicrecord",
            name="project_file",
        ),
        migrations.RemoveField(
            model_name="academicrecord",
            name="project_name",
        ),
    ]
