# Generated by Django 5.2.15 on 2026-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_academicrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('Degree', 'Degree'), ('PG', 'Post Graduation (PG)')], max_length=10)),
                ('semester', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'unique_together': {('course_type', 'semester', 'name')},
            },
        ),
    ]
