# Generated by Django 5.2.15 on 2026-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_subjectcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='assignments',
            field=models.FloatField(default=0),
        ),
    ]
