# Generated by Django 5.1.3 on 2026-03-31 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("activity", "Activity"),
                            ("career", "Career"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discussion", models.TextField()),
                ("guidance", models.TextField()),
                ("follow_up", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.student",
                    ),
                ),
            ],
        ),
    ]
