# Generated by Django 5.1.3 on 2026-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="graduation",
            field=models.CharField(
                choices=[("Degree", "Degree"), ("PG", "Post Graduation (PG)")],
                default="Degree",
                max_length=10,
            ),
        ),
    ]
