# Generated by Django 5.1.3 on 2026-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_student_graduation"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
