# Generated by Django 5.1.3 on 2026-06-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0004_student_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(default="2025-26", max_length=10),
        ),
    ]
