# Generated by Django 5.1.3 on 2026-06-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0005_student_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stage",
            field=models.CharField(
                choices=[
                    ("enrolled", "Enrolled"),
                    ("active", "Active"),
                    ("at_risk", "At Risk"),
                    ("supply", "Supply/Arrear"),
                    ("cleared", "Cleared"),
                    ("career_ready", "Career Ready"),
                    ("graduated", "Graduated"),
                ],
                default="enrolled",
                max_length=20,
            ),
        ),
    ]
