# Generated by Django 5.1.3 on 2026-04-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("Sports", "Sports"),
                            ("Cultural", "Cultural Events"),
                            ("Technical", "Technical Events"),
                            ("Seminar", "Seminars"),
                            ("Hackathon", "Hackathons"),
                            ("NCC", "NCC"),
                            ("NSS", "NSS"),
                            ("Arts", "Arts & Crafts"),
                            ("Literary", "Literary Events"),
                            ("Competition", "Competitions"),
                            ("Workshop", "Workshops"),
                            ("Social", "Social Service"),
                            ("College", "College Activities"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "participation_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Not Participating", "Not Participating"),
                            ("Completed", "Completed"),
                            ("Ongoing", "Ongoing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("achievement", models.CharField(blank=True, max_length=200)),
                ("score", models.CharField(blank=True, max_length=50)),
                ("reason_not_participating", models.TextField(blank=True)),
                ("skills_gained", models.TextField(blank=True)),
                ("guidance_notes", models.TextField(blank=True)),
                ("encouragement_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.student",
                    ),
                ),
            ],
        ),
    ]
