# Generated by Django 5.1.3 on 2026-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityrecord",
            name="upload_file",
            field=models.FileField(
                blank=True, null=True, upload_to="activity_uploads/"
            ),
        ),
    ]
