# Generated by Django 5.2.12 on 2026-06-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_academic_year_student_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="roll_no",
            new_name="roll_number",
        ),
        migrations.AddField(
            model_name="student",
            name="graduation",
            field=models.CharField(
                blank=True,
                choices=[("Degree", "Degree"), ("PG", "PG")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="stage",
            field=models.CharField(
                choices=[
                    ("enrolled", "Enrolled"),
                    ("active", "Active"),
                    ("at_risk", "At Risk"),
                    ("supply", "Supply/Arrear"),
                    ("cleared", "Cleared"),
                    ("career_ready", "Career Ready"),
                    ("graduated", "Graduated"),
                ],
                default="enrolled",
                max_length=20,
            ),
        ),
    ]
