# Generated by Django 5.1.3 on 2026-04-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meeting", "0002_student_mentor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "career_path",
                    models.CharField(
                        choices=[
                            ("higher_studies", "Higher Studies"),
                            ("job_placement", "Job Placement"),
                            ("undecided", "Undecided"),
                        ],
                        default="undecided",
                        max_length=50,
                    ),
                ),
                ("mobile_number", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HigherStudiesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("MSc", "MSc"),
                            ("MTech", "MTech"),
                            ("MBA", "MBA"),
                            ("PhD", "PhD"),
                            ("UPSC", "UPSC - Civil Services"),
                            ("GATE", "GATE"),
                            ("GRE", "GRE - Abroad Studies"),
                            ("Other_Exam", "Other Competitive Exam"),
                        ],
                        max_length=50,
                    ),
                ),
                ("interest_area", models.CharField(max_length=200)),
                ("target_institution", models.CharField(blank=True, max_length=200)),
                ("preparation_level", models.IntegerField(default=0)),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Preparing", "Preparing"),
                            ("Applied", "Applied"),
                            ("Exam Cleared", "Exam Cleared"),
                            ("Admission Received", "Admission Received"),
                            ("Enrolled", "Enrolled"),
                        ],
                        default="Not Started",
                        max_length=50,
                    ),
                ),
                ("exam_score", models.CharField(blank=True, max_length=50)),
                ("guidance_plan", models.TextField(blank=True)),
                ("resources_provided", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career_guidance.careerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placement_office_visits", models.IntegerField(default=0)),
                ("interviews_attended", models.IntegerField(default=0)),
                ("interviews_cleared", models.IntegerField(default=0)),
                (
                    "placement_status",
                    models.CharField(
                        choices=[
                            ("Searching", "Searching"),
                            ("Applied", "Applied"),
                            ("Interview Stage", "Interview Stage"),
                            ("Offer Received", "Offer Received"),
                            ("Placed", "Placed"),
                            ("Still Looking", "Still Looking"),
                        ],
                        default="Searching",
                        max_length=50,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("job_role", models.CharField(blank=True, max_length=200)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("job_location", models.CharField(blank=True, max_length=200)),
                ("offer_date", models.DateField(blank=True, null=True)),
                ("guidance_notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career_guidance.careerprofile",
                    ),
                ),
            ],
        ),
    ]
