# Generated by Django 5.2.15 on 2026-07-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_guidance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_category', models.CharField(choices=[('higher_studies', 'Preparing for Higher Studies'), ('job_placement', 'Preparing for Job Placement'), ('both', 'Both Higher Studies & Job'), ('general', 'General Development')], default='general', max_length=30)),
                ('recorded_date', models.DateField()),
                ('technical_skills_gap', models.TextField(blank=True, help_text='List technical skills the student is missing (e.g. Python, SQL, Excel)')),
                ('soft_skills_gap', models.TextField(blank=True, help_text='Communication, leadership, teamwork gaps etc.')),
                ('communication_level', models.CharField(choices=[('none', 'Not Developed'), ('beginner', 'Beginner'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], default='average', max_length=20)),
                ('leadership_level', models.CharField(choices=[('none', 'Not Developed'), ('beginner', 'Beginner'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], default='average', max_length=20)),
                ('problem_solving_level', models.CharField(choices=[('none', 'Not Developed'), ('beginner', 'Beginner'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], default='average', max_length=20)),
                ('personal_issue', models.CharField(choices=[('none', 'None'), ('confidence', 'Lack of Confidence'), ('anxiety', 'Exam / Interview Anxiety'), ('family', 'Family Pressure / Issues'), ('financial', 'Financial Difficulties'), ('health', 'Health Issues'), ('peer', 'Peer Pressure'), ('motivation', 'Lack of Motivation'), ('time_mgmt', 'Poor Time Management'), ('other', 'Other')], default='none', max_length=30)),
                ('personal_issue_details', models.TextField(blank=True, help_text='Describe the personal challenge in detail')),
                ('emotional_state', models.TextField(blank=True, help_text="Student's current emotional / mental well-being notes")),
                ('mentor_observations', models.TextField(blank=True, help_text='What the mentor observed about the student')),
                ('action_plan', models.TextField(blank=True, help_text='Steps planned to help the student')),
                ('resources_suggested', models.TextField(blank=True, help_text='Books, courses, workshops, counselling suggested')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('in_progress', 'In Progress'), ('improved', 'Improved'), ('resolved', 'Resolved')], default='identified', max_length=20)),
                ('progress_notes', models.TextField(blank=True, help_text='Progress noted at follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_guidance.careerprofile')),
            ],
        ),
    ]
