# Generated by Django 5.2.15 on 2026-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
